### PR TITLE
Add `lts/18/21/FR1.yaml` to get new `freckle-app` with prelude

### PR DESCRIPTION
**Pull request by mjgpy3**
```diff
$ diff lts/18/21/FR1.yaml lts/18/21.yaml 
10c10
<   - freckle-app-1.0.2.3@sha256:f46ab8cadaf8b7890e81891a314db302eb3cd614778e4b13abf9e4a4c24a4f0b,6612
---
>   - freckle-app-1.0.2.2@sha256:93bf2fcac81e63f3dc9a75dc0c557d729f1ff7902dce9ab6da4b1852a80eac13,6445
```

### CODE REVIEW

**Comment by pbrisbin** [comment]
Can you hold this for @cbeav 's `Freckle.App.Database` change too?

**Comment by mjgpy3** [comment]
@pbrisbin of course, no problem at all!

**Comment by mjgpy3** [comment]
Stackage LTS has moved to 18.23.

**Comment by pbrisbin** [comment]
I may have neglected to check if @cbeav knew we've been waiting :grimacing: 

Chris, do you want to get your stuff in this next snapshot or let it go?

**Comment by pbrisbin** [comment]
@mjgpy3 Wanna take over https://github.com/freckle/stackage-snapshots/pull/29 and proceed there?

**Pull request closed without merging**
