### PR TITLE
Add `network-3.1.2.5` to 18.13 snapshot

### PR DESCRIPTION
**Pull request by stackptr**
This pulls in a fix for the package configuration files to recognize `arm64-apple` systems, see: https://github.com/haskell/network/pull/510

### CODE REVIEW

**Review by eborden — CHANGES_REQUESTED** [review]
These snapshots are immutable and cannot be changed once they are deployed. You'll need to introduce a new snapshot for this 18.13.FR1.

**Comment by stackptr** [comment]
Ah, I saw #14 but now see that that was special because the snapshot was utilized.

**Review by eborden — CHANGES_REQUESTED** [review]
This should be `lts/18/13/FR1.yaml`

see: https://github.com/freckle/stackage-snapshots#snapshots

**Review by eborden — APPROVED** [review]
Dope

**Comment by stackptr** [comment]
Sorry for the noise, I had thought this exception when updating the resolver to use this branch was related to the `resolver` field in the YAML and not the path itself:

```
Exception while reading snapshot from https://raw.githubusercontent.com/freckle/stackage-snapshots/corey/13-FR1/lts/18/13-FR1.yaml:
Specified snapshot as file path with "lts-18.13-FR1", but not reading from a local file
Type help for available commands. Press enter to force a rebuild.
```

**Review by eborden — CHANGES_REQUESTED** [review]
Can you add this to the CI matrix?

https://github.com/freckle/stackage-snapshots/blob/main/.github/workflows/ci.yml

**Comment by stackptr** [comment]
Sure!

**Review by eborden — APPROVED** [review]

**Pull request merged**
