### PR TITLE
Use `lts-18.5`.

### PR DESCRIPTION
**Pull request by StevenXL**
Notice that this moves from `fronrow-app` sourced from GitHub to
`freckle-app` sourced from Hackage.

Notice that this moves from `fronrow-app` sourced from GitHub to
`freckle-app` sourced from Hackage.

`diff lts/18/2.yaml lts/18/5.yaml` yields:

```
2c2
< resolver: lts-18.2
---
> resolver: lts-18.5
9a10
>   - freckle-app-1.0.0.1@sha256:2525db3c67b3be3f9ff36a1511901b3f237018c96aeab743c1c9cc28dea30e44,5318
15,18d15
<   # https://app.asana.com/0/1160405925455011/1200183896199567/f
<   - git: https://github.com/freckle/frontrow-app
<     commit: 0a283e6f5fbbe21d9f63438432137f38cce65a5d
<

```

### CODE REVIEW

**Review by pbrisbin — APPROVED** [review]
LGTM; I assume you've done the steps in https://github.com/freckle/stackage-snapshots#creating-a-new-snapshot ?

**Comment by StevenXL** [comment]
> https://github.com/freckle/stackage-snapshots#creating-a-new-snapshot

I did indeed. I left "outdated" dependencies that are needed to be able to install build tools. For example, we are using opt-parse v0.15 from Hackage, rather than relying on v0.16 in the resolver, because stylish-haskell has an upper bound of <0.16.

**Comment by pbrisbin** [comment]
Yeah, I noticed that too. I wonder if we should open an Issue on Stylish about it.

**Comment by StevenXL** [comment]
> Yeah, I noticed that too. I wonder if we should open an Issue on Stylish about it.

Done. https://github.com/haskell/stylish-haskell/issues/377

**Pull request merged**
